apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Port exposed to the public
      targetPort: 3000  # Port where the container is running
  type: ClusterIP
