apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
  type: ClusterIP
